name: SottoApp
options:
  bundleIdPrefix: dev.sotto
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  SottoApp:
    type: application
    platform: macOS
    sources:
      - Sources
      - Generated
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.sotto.app
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: SottoApp.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/../target/release"
        OTHER_LDFLAGS:
          - "-lsotto_core"
          - "-framework"
          - "Accelerate"
          - "-framework"
          - "CoreML"
          - "-framework"
          - "Metal"
          - "-framework"
          - "MetalKit"
          - "-framework"
          - "CoreAudio"
          - "-framework"
          - "AudioToolbox"
          - "-framework"
          - "Security"
        SWIFT_OBJC_BRIDGING_HEADER: ""
        SWIFT_IMPORT_PATHS:
          - "$(PROJECT_DIR)/Generated"
    info:
      path: Resources/Info.plist
