name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Dikto? We'd love to hear it.

        **Tip:** Check [Discussions > Ideas](https://github.com/diktoapp/dikto/discussions/categories/ideas) first — your idea may already be there. Upvoting existing ideas helps us prioritize.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve? What are you trying to do?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
